### ISSUE TITLE
"location of Error in if (size_MB > 100) { : missing value where TRUE/FALSE needed"

### ISSUE THREAD

**Issue by mgomezgoiri** [bradleyjeck/epanetReader#36]
Hi everyone, recently, we have started a project about calibration of water distribution networks and location of leakages, and we want to make the first optimization problem approach in R. Looking for more information, we found out epanetReader packages. First of all, we are trying to read INP file with this package, but we are having troubles to get it. R prints next error:
"location of Error in if (size_MB > 100) { : missing value where TRUE/FALSE needed"

My INP file is smaller than 100 MB (1526 kB). Have anyone had the same error? Would you help me solving this error?

Thank you in advance.

**Comment by bradleyjeck** [comment]
hi @mgomezgoiri - what command are you running to get the error?

**Comment by mgomezgoiri** [comment]
After some trials, I put my INP file in the same file path (to be sure that it wasn't because of the path).
#First own trial:prueba:zarautz.inp (same file path)

inp <- file.path( find.package("epanetReader"), "extdata","pruebas:zarautz.inp")
n2 <- epanetReader::read.inp(inp)`

After that, console replies me the error:

location of Error in if (size_MB > 100) { : missing value where TRUE/FALSE needed

**Comment by bradleyjeck** [comment]
Ahh, the example of using `file.path( find.packages( . . . `  is to locate the file Net1.inp that is distributed with the package so that copying and pasting the example code will work.  

In your case, you should set the working directory for your R session to the same directory where your .inp file resides.   So the if the file is in C:\work\project\ then use `setwd("C:/work/project")` to move your R session there.  Then ` n <- read.inp("Pruebas:zarautz.inp") `  to read the network file into R.

Let me know if that works?

**Comment by mgomezgoiri** [comment]
It works! Thank you so much.

Regarding the package and our project main objective, I have seen that there are interest in calling EPANET executable. Are there some script related with?

Thank you again,

**Comment by bradleyjeck** [comment]
Glad to know this works.

As for calling the epanet executable.  There is interest and I'm hoping to release something later this summer.  Meanwhile, If you have the epanet executable in your system path variable you can call it from within R.  On my windows PC it works like this, assuming your working directory contains Net1.inp :  
```
system("epanet2d Net1.inp Net1.rpt") 
```
